model_type: timbre
sample_rate: 22050

# 我加的，调整水印强度
wm_ratio: 1.0

message:
  len: 30

process:
  audio:
    or_sample_rate: 16000
    sample_rate: ${sample_rate}
    max_wav_value: 32768.0
    win_len: 256
    max_len: 176000

  mel:
    n_fft: 1024
    hop_length: 256
    win_length: 1024

model:
  structure:
    transformer: 0
    conv2: 0
    conv2mel: 1
    mel: 1
    share: 0
    vocoder_step: 0
    ab: 0

  robust: 0

  dim:
    embedding: 512

  layer:
    nlayers_encoder: 6
    attention_heads_encoder: 8
    nlayers_decoder: 6
    attention_heads_decoder: 8

  wm:
    kernel_size: 3
    n_temporal_layer: 2

  audio:
    kernel_size: 3
    n_temporal_layer: 2

  conv_module:
    hidden_size: 32
    kernel_size: 13
    n_temporal_layer: 5
    n_linear_layer: 0
    hidden_dim: 512

  conv2:
    block: 'skip' #'skip', 'relu'
    layers_CE: 3
    layers_EM: 4
    hidden_dim: 64

  test:
    model_path: "./ckpts/timbre_ckpt/compressed_none-conv2_ep_20_2023-02-14_02_24_57.pth.tar"
    model_name: False
    index: -1

# 我自己加的，把vocoder信息放在这里
vocoder:
  vocoder_config: "./third_party/raw_bench/wm_ckpts/timbre/watermarking_model/hifigan/config.json"
  vocoder_checkpoint: "./third_party/raw_bench/wm_ckpts/timbre/watermarking_model/hifigan/model/VCTK_V1/generator_v1"